apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataspace-operator.fullname" . }}
  labels:
    {{- include "dataspace-operator.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
  ASPNETCORE_URLS: "http://+:8080"
  Issuer__Did: {{ .Values.issuer.did | quote }}
  ConnectionStrings__ConnectionString: {{ include "dataspace-operator.connectionString" . | quote }}
